### ISSUE TITLE
Showing network error

### ISSUE THREAD

**Issue by InstaTechHD** [Dev-Dylann/weebixx#1]
Hi, the website is showing network error 
![Screenshot_2023-09-28-10-00-36-819_com android chrome](https://github.com/Dev-Dylann/weebixx/assets/68559185/e83d3b55-5013-4007-88dc-ea9ccb2cfc1e)

**Comment by Dev-Dylann** [comment]
This was due to a cors policy error which I believe is fixed now. You can check to confirm
